const chanelListYa = [
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/pervyy-16",
    chnl: "Первый Канал",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/850/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/rossiya-1-31",
    chnl: "Россия1",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1271/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/match-tv-49",
    chnl: "МатчТВ",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/2060/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/ntv-11",
    chnl: "НТВ",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1395/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/pyatyy-kanal-12",
    chnl: "Пятый канал",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/963/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/kultura-14",
    chnl: "Культура",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1169/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/rossiya-24-3",
    chnl: "Россия24",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/2519/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/karusel-20",
    chnl: "Карусель",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1162/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/obshchestvennoe-televidenie-rossii-51",
    chnl: "ОТР",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1670/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/tv-centr-32",
    chnl: "ТВЦ",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/948/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/ren-30",
    chnl: "РенТВ",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1148/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/spas-52",
    chnl: "Спас",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1193/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/sts-8",
    chnl: "СТС",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1112/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/domashniy-5",
    chnl: "Домашний",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1051/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/tv-3-17",
    chnl: "ТВ3",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1091/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/pyatnica-42",
    chnl: "Пятница",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1671/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/zvezda-15",
    chnl: "Звезда",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/986/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/mir-54",
    chnl: "МИР",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/717/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/tnt-33",
    chnl: "ТНТ",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/2287/",
  },
  {
    adress: "https://tv.yandex.ru",
    prog: "/channel/muz-tv-55",
    chnl: "МУЗТВ",
    mailAddress: "https://tv.mail.ru",
    mailprog: "/moskva/channel/1111/",
  },
];

export default chanelListYa;
