# Generated by Django 3.2.9 on 2021-11-25 20:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название программы')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Дата')),
                ('time_start', models.CharField(max_length=6, verbose_name='Время начала')),
                ('time_end', models.CharField(max_length=6, null=True, verbose_name='Время конца')),
                ('chanel', models.CharField(max_length=100, null=True, verbose_name='Название канала')),
                ('image', models.CharField(max_length=500, null=True, verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='ProgImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(max_length=500, verbose_name='Картинка')),
                ('id_Program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.programs')),
            ],
        ),
    ]
